DROP TABLE IF EXISTS `employees`;
CREATE TABLE `employees` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `employee_id` varchar(25) NOT NULL,
  `fullname` varchar(100) NOT NULL,
  `gender` enum('Male','Female') NOT NULL,
  `email` varchar(100) NOT NULL,
  `group_company` varchar(50) NOT NULL,
  `designation` varchar(255) NOT NULL,
  `designation_code` varchar(255) DEFAULT NULL,
  `designation_name` varchar(255) DEFAULT NULL,
  `job_level` varchar(50) NOT NULL,
  `company_name` varchar(50) NOT NULL,
  `contribution_level_code` varchar(255) DEFAULT NULL,
  `work_area_code` varchar(50) NOT NULL,
  `office_area` varchar(50) NOT NULL,
  `manager_l1_id` varchar(25) NOT NULL,
  `manager_l2_id` varchar(25) NOT NULL,
  `employee_type` enum('Permanent','Contract','Probation','Service Bond') NOT NULL,
  `unit` varchar(255) NOT NULL,
  `personal_email` varchar(100) DEFAULT NULL,
  `personal_mobile_number` varchar(25) DEFAULT NULL,
  `whatsapp_number` varchar(25) DEFAULT NULL,
  `date_of_birth` date DEFAULT NULL,
  `place_of_birth` varchar(50) DEFAULT NULL,
  `nationality` varchar(50) DEFAULT NULL,
  `religion` varchar(50) DEFAULT NULL,
  `marital_status` varchar(50) DEFAULT NULL,
  `citizenship_status` varchar(50) DEFAULT NULL,
  `ethnic_group` varchar(50) DEFAULT NULL,
  `homebase` varchar(100) DEFAULT NULL,
  `current_address` text DEFAULT NULL,
  `current_city` varchar(50) DEFAULT NULL,
  `permanent_address` text DEFAULT NULL,
  `permanent_city` varchar(50) DEFAULT NULL,
  `blood_group` varchar(50) DEFAULT NULL,
  `tax_status` varchar(50) DEFAULT NULL,
  `bpjs_tk` varchar(50) DEFAULT NULL,
  `bpjs_ks` varchar(50) DEFAULT NULL,
  `ktp` varchar(50) DEFAULT NULL,
  `kk` varchar(50) DEFAULT NULL,
  `npwp` varchar(50) DEFAULT NULL,
  `mother_name` varchar(50) DEFAULT NULL,
  `bank_name` varchar(50) DEFAULT NULL,
  `bank_account_number` varchar(50) DEFAULT NULL,
  `bank_account_name` varchar(50) DEFAULT NULL,
  `date_of_joining` date NOT NULL,
  `users_id` varchar(36) DEFAULT NULL,
  `access_menu` longtext DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `employees` MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
